language: node_js
node_js:
  - stable
  - "10"
cache:
  directories:
    - ~/.yarn-cache
    - .jest
before_script:
  - yarn global add yarn@1.12.3 -- tilde
install:
  - yarn install
script:
  - yarn test --ci
  - yarn lint