version: 2
publish: &publish
  working_directory: ~/loplop-native
  docker:
    - image: circleci/node:10.13.0
  steps:
    - checkout
    - restore_cache:
        name: Restore yarn package cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        command: yarn install
    - save_cache:
        name: Save yarn package cache
        paths:
          - ~/.cache/yarn
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Login into Expo
        command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - run:
        name: Publish to Expo
        command: npx expo publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  build_and_test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install 
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test

  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  workflow:
    jobs:
      - build_and_test
      - publish_to_expo_dev:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: master